<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Google Ads</name>
   <tag></tag>
   <elementGuidId>397c6014-93ca-45ed-ac96-f23f34457c94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ad6648fbfc8f-0']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ng-option-label.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9f0b9ac1-0dd3-4bcc-81c5-138b48924693</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option-label ng-star-inserted</value>
      <webElementGuid>562afd6c-d351-4fb3-a072-978307408595</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Google Ads</value>
      <webElementGuid>f264e736-04a2-4420-a358-eafe078ed8e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ad6648fbfc8f-0&quot;)/span[@class=&quot;ng-option-label ng-star-inserted&quot;]</value>
      <webElementGuid>adc163de-6c64-41e3-9d23-70b87745ed4b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ad6648fbfc8f-0']/span</value>
      <webElementGuid>50b2bd87-95c8-46e0-91a3-76c35ecb1a24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span</value>
      <webElementGuid>f85fd34b-79c0-46eb-8bc4-880ca5d455f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Google Ads' or . = 'Google Ads')]</value>
      <webElementGuid>69707092-3ddb-48f3-8033-13255bd92624</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
