<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_mat-select-arrow-wrapper ng-tns-c110-14</name>
   <tag></tag>
   <elementGuidId>d9ed673f-29e5-4e30-a5db-24b0b14f4364</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mat-select-arrow-wrapper.ng-tns-c110-14</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-select[@id='mat-select-4']/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a8df4aaa-4f12-4cd2-9362-df1ddbb77d39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-select-arrow-wrapper ng-tns-c110-14</value>
      <webElementGuid>f3ec7334-c285-4f2f-8021-dffde4645d0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-select-4&quot;)/div[@class=&quot;mat-select-trigger ng-tns-c110-14&quot;]/div[@class=&quot;mat-select-arrow-wrapper ng-tns-c110-14&quot;]</value>
      <webElementGuid>5ec01384-32bb-4f4a-a6cf-6c5e00926c46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-select[@id='mat-select-4']/div/div[2]</value>
      <webElementGuid>ccfe4668-81a2-44a0-b2eb-77bd466be722</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-target-vs-spend-column-chart/div/app-sb-bar-chart/div/mat-paginator/div/div/div/mat-form-field/div/div/div/mat-select/div/div[2]</value>
      <webElementGuid>997d5ee9-3925-4f3a-82f8-aef04c34e3f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
