<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Items per page</name>
   <tag></tag>
   <elementGuidId>6f677acf-b531-4e5e-866c-6818642d9839</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mat-paginator-page-size-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='table1']/app-mtd-spend-column-chart/div/app-sb-bar-chart/div/mat-paginator/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>33ab5416-5f4d-4662-9793-5f69d7eadf02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-paginator-page-size-label</value>
      <webElementGuid>4081a9e3-3ffb-46ca-a176-d7db7a21b1a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Items per page: </value>
      <webElementGuid>305abf94-4c29-46aa-a243-79785d3e525f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-tab-content-1-2&quot;)/div[@class=&quot;mat-tab-body-content ng-tns-c164-7 ng-trigger ng-trigger-translateTab&quot;]/app-mtd-viwes[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;col-span-full tab-wrapper&quot;]/div[@class=&quot;reports-row&quot;]/div[@class=&quot;row-wrapper grid grid-cols-4 gap-4&quot;]/div[@id=&quot;table1&quot;]/app-mtd-spend-column-chart[1]/div[@class=&quot;col-span-full&quot;]/app-sb-bar-chart[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;container&quot;]/mat-paginator[@class=&quot;mat-paginator&quot;]/div[@class=&quot;mat-paginator-outer-container&quot;]/div[@class=&quot;mat-paginator-container&quot;]/div[@class=&quot;mat-paginator-page-size ng-star-inserted&quot;]/div[@class=&quot;mat-paginator-page-size-label&quot;]</value>
      <webElementGuid>c819d7a5-a02c-4d8e-808f-42c807e82645</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='table1']/app-mtd-spend-column-chart/div/app-sb-bar-chart/div/mat-paginator/div/div/div/div</value>
      <webElementGuid>43071db8-a0fc-4884-92d7-b86b4179a2ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-paginator/div/div/div/div</value>
      <webElementGuid>3e28bec1-b937-482d-8c4b-7ded8592da5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Items per page: ' or . = ' Items per page: ')]</value>
      <webElementGuid>31ccb8e1-982f-4961-bc32-cdde3381ec2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
