<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_password</name>
   <tag></tag>
   <elementGuidId>e6c6444a-6af7-476b-b3d3-d434c06a9ed2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#password1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='password1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4c4d2c8d-687b-46ed-9567-9e70339aea83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>c8815427-a5e9-4c59-ada8-619194c08d2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>password1</value>
      <webElementGuid>5a0bb642-cdc9-401f-a7a0-474538343b46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>0aad18b6-b9c9-4315-a03a-3448c4c79d1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your password</value>
      <webElementGuid>68a602a8-f6f6-4f00-9435-6a0be82b0594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>fc269a5e-3b40-40b6-80bd-6bfe9f729260</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>01e616d0-9994-4e64-b453-d6a8530ac8af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login-field ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>c5d9d491-9742-43fb-86bf-83ce2607ef2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;password1&quot;)</value>
      <webElementGuid>58414531-d6ae-4629-82ee-44f04cf91ba5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='password1']</value>
      <webElementGuid>50827492-e9c1-4244-8cf0-807f4f7cb647</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='kc-form-login1']/input[2]</value>
      <webElementGuid>02b89f50-cf77-4d4f-b86f-179b1c8629cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>1b8e05f1-f6a2-4919-ad59-98aa2a6eb492</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'password1' and @placeholder = 'Enter your password' and @name = 'password']</value>
      <webElementGuid>fa7550b7-b735-4aed-a29f-7eea1d1bb699</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
