<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_spinner diagonal part-2</name>
   <tag></tag>
   <elementGuidId>6744972c-c8da-424a-a06e-102bf51fc426</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.spinner.diagonal.part-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>56d71710-ad8c-40b7-bda5-3bc57120fd67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>spinner diagonal part-2</value>
      <webElementGuid>fa4b558b-7682-4783-b1ee-528ffbdea90c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;sidebaractive&quot;]/app-root[1]/app-layout[@class=&quot;ng-star-inserted&quot;]/div[1]/div[1]/app-side-nav[1]/aside[@class=&quot;app-side-nav&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;RespMenuIcon&quot;]/label[@class=&quot;sidebarIconToggle&quot;]/div[@class=&quot;spinner diagonal part-2&quot;]</value>
      <webElementGuid>edc9c697-7f7f-4e79-af8d-0069a2e54ea4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div[3]</value>
      <webElementGuid>95ec7673-3701-43b7-829d-236523d35931</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
