<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_signOut</name>
   <tag></tag>
   <elementGuidId>27730d97-b6fd-4a31-b58d-aa0a9e782eec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='signOut']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#signOut</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>350d0948-e8b2-4977-9ebd-50315e984c71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b9a27bb4-230f-450c-a6f6-f9e7aa0d577f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mattooltip</name>
      <type>Main</type>
      <value>Logout</value>
      <webElementGuid>c7214d4b-0fd2-42de-8dc9-a95afad6432d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signOut</value>
      <webElementGuid>144ae674-0d78-4c45-80f0-31adc5e17614</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>signOut</value>
      <webElementGuid>4ba7e36c-f9f9-4a9d-8d04-9f85b8e86174</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-tooltip-trigger fa fa-sign-out</value>
      <webElementGuid>ce610c48-34e1-456f-9651-563a19536770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>cdk-describedby-message-rbp-1-2</value>
      <webElementGuid>ea892345-f3f2-4c4c-9cd0-fda473fbd9c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cdk-describedby-host</name>
      <type>Main</type>
      <value>rbp-1</value>
      <webElementGuid>9c02f0d5-3cbf-4859-bb2e-a6db346166d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signOut&quot;)</value>
      <webElementGuid>272a457a-679e-4f8c-9e62-5c2f2857f294</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='signOut']</value>
      <webElementGuid>c4ffc35f-26c6-4aa5-b6f0-488efa62b546</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/i</value>
      <webElementGuid>33332a12-c6bc-4383-99ca-2e296b39722b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'signOut' and @name = 'signOut']</value>
      <webElementGuid>3b8a5f35-a990-4838-95f5-7188fe9bf435</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
