<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Performance</name>
   <tag></tag>
   <elementGuidId>33b49ce0-69ab-4d77-8786-183b8c80c9e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>fd7de455-d65d-4bf7-bf2d-d0803be9b151</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlinkactive</name>
      <type>Main</type>
      <value>activeLink</value>
      <webElementGuid>3fda1c32-c86b-4a81-b5f3-4644b9095f91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>menu-item</value>
      <webElementGuid>8c0643a9-ae02-4606-8c05-88e591d4a957</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-tooltip-trigger menu-item ng-star-inserted cdk-focused cdk-mouse-focused</value>
      <webElementGuid>e5c800ff-bde9-4a7b-a278-ee11bb3c8f84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e98bab40-981f-4111-af83-6d1817461d32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu-item-2</value>
      <webElementGuid>e3c23406-4bdb-4aa1-8f8d-4299f3b73366</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>cdk-describedby-message-rbp-1-13</value>
      <webElementGuid>2f0c686e-0202-4fb4-94a3-deb99c0f9082</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cdk-describedby-host</name>
      <type>Main</type>
      <value>rbp-1</value>
      <webElementGuid>d913b8b3-3832-4a13-86b3-a0081a49646d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Performance</value>
      <webElementGuid>c49be1fd-eb41-474e-9e8d-5c033d29c0fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-2&quot;)</value>
      <webElementGuid>7f606e43-9b2c-4ce6-a6ce-af2b955ee2b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='menu-item-2']</value>
      <webElementGuid>97d48630-ccf4-449b-a066-547a60728dc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='sidebarMenu']/li[3]</value>
      <webElementGuid>74d477ee-33b1-4a12-b57c-36ea2b8fe4fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]</value>
      <webElementGuid>e0219413-8d00-486e-8233-7b7020cb38d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@name = 'menu-item' and @id = 'menu-item-2' and (text() = 'Performance' or . = 'Performance')]</value>
      <webElementGuid>c002cd23-1f4e-4b3c-b39a-fe6b8101de21</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
