<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Select Businessline</name>
   <tag></tag>
   <elementGuidId>48acb7f9-737f-4775-b375-ab9a6ed3e7cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#filter-Businessline > div.ng-select-container.ng-has-value > div.ng-value-container > div.ng-placeholder</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ng-select[@id='filter-Businessline']/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>00002716-e6d0-4bd8-aede-33a32bf97bb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-placeholder</value>
      <webElementGuid>b0fc78ab-44d5-4b93-b68f-ee1c9e200d04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Businessline</value>
      <webElementGuid>778da222-7163-4a72-b621-89be7bd25a18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filter-Businessline&quot;)/div[@class=&quot;ng-select-container ng-has-value&quot;]/div[@class=&quot;ng-value-container&quot;]/div[@class=&quot;ng-placeholder&quot;]</value>
      <webElementGuid>35eb1988-e8f8-41e2-b2ce-1d6fdcb1c412</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-select[@id='filter-Businessline']/div/div/div</value>
      <webElementGuid>1becda11-95bc-4d26-8de5-511b41814fc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ng-select/div/div/div</value>
      <webElementGuid>c71c2c41-52b6-4123-a538-babeb6d4938e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Select Businessline' or . = 'Select Businessline')]</value>
      <webElementGuid>4db83bf1-c978-4e87-a6dc-75bf613a46fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
