<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>f48cbd3d-45e4-46d8-9b5e-e8257d21fae5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fullscreen-button > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='fullscreen-button']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2c8c24a1-f533-461a-9991-6da884f315fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>17</value>
      <webElementGuid>e86eab28-8f9d-4951-b0d5-03fa4fd73d97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/images/full-screen_img.png</value>
      <webElementGuid>ee38688f-8225-4225-9a89-5460fdb06627</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fullscreen-button&quot;)/img[1]</value>
      <webElementGuid>f05ab25c-86c3-4617-ad39-790805a367fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='fullscreen-button']/img</value>
      <webElementGuid>be58cc7b-d4c1-417c-a634-49ade671f2c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/img</value>
      <webElementGuid>1799ad76-178b-4551-a5f2-644b3b1ae399</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'assets/images/full-screen_img.png']</value>
      <webElementGuid>37bb26ce-2f4c-4e29-b97e-9c279e1ec110</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
