<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ng-arrow-wrapper_1_2</name>
   <tag></tag>
   <elementGuidId>9158c4f0-2af8-4439-a489-d609bad0918b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-tab-body[@id='mat-tab-content-1-0']/div/app-unext-campaign-metric-tabel/div/div/div[2]/app-filter-panel/div/div/div/div/div[3]/ng-select/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ng-select.ng-select-multiple.ng-select-searchable.ng-select-clearable.ng-select.ng-pristine.ng-valid.ng-star-inserted.ng-select-focused.ng-touched.ng-select-bottom > div.ng-select-container > span.ng-arrow-wrapper</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ab382bfb-c15b-469e-84a4-b529138916ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-arrow-wrapper</value>
      <webElementGuid>80d9c43a-377f-42bb-b503-5d0e6e6313f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-tab-content-1-0&quot;)/div[@class=&quot;mat-tab-body-content ng-tns-c164-3 ng-trigger ng-trigger-translateTab&quot;]/app-unext-campaign-metric-tabel[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;col-span-full tab-wrapper&quot;]/div[@class=&quot;filter-row grid grid-cols-10&quot;]/div[@class=&quot;xmd:col-span-5 md:col-span-7 lg:col-span-8 col-span-7 p-2&quot;]/app-filter-panel[1]/div[@class=&quot;wrapper ng-star-inserted&quot;]/div[@class=&quot;grid grid-cols-10 filter-panel-wrapper align-items-center&quot;]/div[@class=&quot;col-span-full xmd:col-span-full&quot;]/div[@class=&quot;grid grid-cols-12&quot;]/div[@class=&quot;filter-wrapper md:col-span-3 xs:col-span-12 xmd:col-span-4 4k:col-span-2 ng-star-inserted&quot;]/ng-select[@class=&quot;ng-select-multiple ng-select-searchable ng-select-clearable ng-select ng-pristine ng-valid ng-star-inserted ng-select-focused ng-touched ng-select-bottom&quot;]/div[@class=&quot;ng-select-container&quot;]/span[@class=&quot;ng-arrow-wrapper&quot;]</value>
      <webElementGuid>b71151f0-c187-4300-a753-e486076bc6e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-1-0']/div/app-unext-campaign-metric-tabel/div/div/div[2]/app-filter-panel/div/div/div/div/div[3]/ng-select/div/span</value>
      <webElementGuid>5aa9991c-db30-4296-a658-b6a009b37e54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/ng-select/div/span</value>
      <webElementGuid>b4b076eb-79fc-4373-82ec-6389c0e6c8cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
