<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_2016  2039</name>
   <tag></tag>
   <elementGuidId>aabcfc56-6916-4047-bccf-fc6062cf33dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-calendar-button-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='mat-calendar-button-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ef4a5e29-8ff2-4f81-8c2d-c427ee36ed38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-calendar-button-0</value>
      <webElementGuid>b17e77e6-0d86-4ac3-a49b-c660b8712199</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2016 – 2039</value>
      <webElementGuid>344c9f43-6e62-41c9-baf0-82540dca73d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-calendar-button-0&quot;)</value>
      <webElementGuid>f5e75e93-0446-4951-9d54-27cd0cc8a9b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='mat-calendar-button-0']</value>
      <webElementGuid>3979de9e-3d33-498b-b1fb-dc95498e7c82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-calendar[@id='mat-datepicker-1']/mat-calendar-header/div/div/button/span/span</value>
      <webElementGuid>9a11a659-fc1f-4601-a69c-89dcfecbeb88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span/span</value>
      <webElementGuid>50ae848f-42e1-4e43-8490-7dbc45d0df3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'mat-calendar-button-0' and (text() = '2016 – 2039' or . = '2016 – 2039')]</value>
      <webElementGuid>b0ffe0ad-d16f-46bc-9048-ee6044799daf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
