<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>69ba770b-d1e5-4cf2-a4a0-a4e4d0b906c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fullscreen-button > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='fullscreen-button']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ecbaaec3-afa9-4eda-8c23-5d3b245791ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>17</value>
      <webElementGuid>1e0f1856-f928-4187-a37d-be1481677da8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/images/full-screen_img.png</value>
      <webElementGuid>6054c97a-95d6-4779-a0e7-39b2c9e5699e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fullscreen-button&quot;)/img[1]</value>
      <webElementGuid>2262d989-77f8-423d-9893-9da6f77113d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='fullscreen-button']/img</value>
      <webElementGuid>f2c8bf53-4049-4c7d-9533-204c25215c85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/img</value>
      <webElementGuid>0f2e508f-1e38-4df1-9c5d-a35ab44c0be1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'assets/images/full-screen_img.png']</value>
      <webElementGuid>ba7235d5-a184-45ff-9a11-1dc1fdf6ed73</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
