<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>be746272-d76e-4316-82cb-e33b0ee8e31c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fullscreen-button > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='fullscreen-button']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c6615afe-5c7c-486b-a231-3466706f475c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>17</value>
      <webElementGuid>2b72c1a6-73a2-4d24-ba1f-428312031ab0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/images/full-screen_img.png</value>
      <webElementGuid>18c7fe46-4261-436d-8dc4-384329bdf0fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fullscreen-button&quot;)/img[1]</value>
      <webElementGuid>d502b1f6-3a58-45a8-a57e-7903ed28b656</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='fullscreen-button']/img</value>
      <webElementGuid>d74c4aac-487a-4926-bf63-00558511e72f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/img</value>
      <webElementGuid>5c785dbe-bc83-4b9d-b4e9-52c7f6e0d836</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'assets/images/full-screen_img.png']</value>
      <webElementGuid>afe34f8c-1123-4433-839b-d98dc6cf9645</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
