<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_admetrics_menuIcon</name>
   <tag></tag>
   <elementGuidId>8654050c-3930-4b10-8f29-ccf205f535da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-0']/div/i/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.menuIcon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>80eb09d4-b663-4462-9f3d-d10cc6e3b951</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menuIcon</value>
      <webElementGuid>94f252c6-aacb-44a0-86cf-2461b6a4d02c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/images/spend.png</value>
      <webElementGuid>db757a9a-2e4d-43b6-a8b1-b80e1c05d9ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-0&quot;)/div[@class=&quot;btn active inside btnActive&quot;]/i[@class=&quot;img&quot;]/img[@class=&quot;menuIcon&quot;]</value>
      <webElementGuid>02966855-6f8b-4f11-9d61-41f9b7c2909b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-0']/div/i/img</value>
      <webElementGuid>66cfee44-7fbc-4240-b1d1-2f5c05b88f09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i/img</value>
      <webElementGuid>e6cf26c1-e568-4ba1-87de-b9cdadb8c2b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'assets/images/spend.png']</value>
      <webElementGuid>bf04fa5f-ba91-49b9-89da-21bbfe7ea0b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
