<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Spend Report</name>
   <tag></tag>
   <elementGuidId>a9df8852-6ad3-48a2-9530-e30d745430d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>5426127a-d87c-492a-a456-bbaf8b068275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlinkactive</name>
      <type>Main</type>
      <value>activeLink</value>
      <webElementGuid>e726bd7c-85ef-47ee-8959-98456ab0ad51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>menu-item</value>
      <webElementGuid>398770cc-d17d-4417-9b4a-e5dd12a5d1cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-tooltip-trigger menu-item ng-star-inserted activeLink cdk-focused cdk-mouse-focused</value>
      <webElementGuid>197b6545-5c24-4a5f-adc2-0fa0fd9f7d85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e13aa9e1-42f5-4390-b45f-0c71cc7c6adc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu-item-0</value>
      <webElementGuid>7041a08e-bc00-4462-9ed0-9715cea21b07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>cdk-describedby-message-tjd-1-3</value>
      <webElementGuid>d1f19004-874e-4b80-aab7-1b2e762028f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cdk-describedby-host</name>
      <type>Main</type>
      <value>tjd-1</value>
      <webElementGuid>a15ce217-f3a2-4132-aeab-8a594bce2b22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Spend Report</value>
      <webElementGuid>db89cce0-54f9-4b99-837a-68952d257888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-0&quot;)</value>
      <webElementGuid>1a5fa0a5-d5d1-42b2-97eb-5b404075569e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='menu-item-0']</value>
      <webElementGuid>0d8db27f-7fee-47c5-b041-4169eb8a529f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='sidebarMenu']/li</value>
      <webElementGuid>e64bf864-0acd-422e-90b4-824cfa7a9355</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='admetrics'])[1]/following::li[1]</value>
      <webElementGuid>93e873d5-d995-4ef3-b18a-d635d504d851</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Performance Report'])[1]/preceding::li[1]</value>
      <webElementGuid>65ee4e82-8f02-4c5d-9e50-8b3cd7831645</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li</value>
      <webElementGuid>97d80e11-bd61-45f5-8295-4dfb7b91e3ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@name = 'menu-item' and @id = 'menu-item-0' and (text() = 'Spend Report' or . = 'Spend Report')]</value>
      <webElementGuid>9726aa26-ec9b-4ab7-b12a-400357b6be6c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
