<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Daily Buyer CAC Report</name>
   <tag></tag>
   <elementGuidId>a13440c0-9402-46a2-aa42-79f81c9acf09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-tab-label-1-2 > div.mat-tab-label-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mat-tab-label-1-2']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>900852e4-fa7f-427b-9793-5f3a91ff4935</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-tab-label-content</value>
      <webElementGuid>a69f9433-8638-481e-a1bc-736683c1b4b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Daily Buyer CAC Report</value>
      <webElementGuid>9cdaf0d8-6dcd-44d7-9da5-95e0e6aa9714</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-tab-label-1-2&quot;)/div[@class=&quot;mat-tab-label-content&quot;]</value>
      <webElementGuid>8e04b833-c285-4b8c-b0de-66493f94b41a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mat-tab-label-1-2']/div</value>
      <webElementGuid>f71af8c6-ca83-448b-815f-b123027195c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div</value>
      <webElementGuid>f6953e24-ece4-41e0-9f3d-d8ed4bb237cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Daily Buyer CAC Report' or . = 'Daily Buyer CAC Report')]</value>
      <webElementGuid>80914bc0-b713-40d3-b3e5-16dd96f55c31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
