<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>polygon_1</name>
   <tag></tag>
   <elementGuidId>66362f49-b8de-4d01-a6a7-92949d24f870</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>polygon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>polygon</value>
      <webElementGuid>0c033c90-b72e-4935-b5ed-0422db58b66a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>points</name>
      <type>Main</type>
      <value>0,0 5,5 10,0</value>
      <webElementGuid>3d8a79c0-38a0-4fa5-b652-66ea7188602f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-datepicker-0&quot;)/mat-calendar-header[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;mat-calendar-header&quot;]/div[@class=&quot;mat-calendar-controls&quot;]/button[@class=&quot;mat-focus-indicator mat-calendar-period-button mat-button mat-button-base cdk-focused cdk-mouse-focused&quot;]/span[@class=&quot;mat-button-wrapper&quot;]/svg[@class=&quot;mat-calendar-arrow mat-calendar-invert&quot;]/polygon[1]</value>
      <webElementGuid>ff925e01-0178-404c-ad4a-1f3ebbd3e9a8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
