<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Discovery_Custom_MBA</name>
   <tag></tag>
   <elementGuidId>d6270527-0e38-42ab-8cdb-ab715acf1c8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='a4cecaed5c61-6']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#a4cecaed5c61-6 > div.row.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1801826f-0314-4e9e-bef4-22161334f7b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row ng-star-inserted</value>
      <webElementGuid>b436ea94-291c-4511-9008-1f68aadd7bb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Discovery_Custom_MBA </value>
      <webElementGuid>dee08589-bcff-44e5-bffe-440e333b38e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a4cecaed5c61-6&quot;)/div[@class=&quot;row ng-star-inserted&quot;]</value>
      <webElementGuid>0425d1af-81cc-412a-86a5-3edf3967ebdc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='a4cecaed5c61-6']/div</value>
      <webElementGuid>e57b9913-ed9d-48c9-8b4c-a6a94577f4d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div</value>
      <webElementGuid>14c0ed18-e444-476c-9297-dabd8587c5f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Discovery_Custom_MBA ' or . = ' Discovery_Custom_MBA ')]</value>
      <webElementGuid>80f9aceb-f2a5-488f-8282-98bee8485da3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
