<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_text</name>
   <tag></tag>
   <elementGuidId>286f275d-df49-43d6-998d-4bb3ae14efda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ng-select.ng-select-multiple.ng-select-searchable.ng-select-clearable.ng-select.ng-untouched.ng-pristine.ng-valid.ng-star-inserted.ng-select-focused.ng-select-bottom.ng-select-opened > div.ng-select-container.ng-has-value > div.ng-value-container > div.ng-input > input[type=&quot;text&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>13dd2c41-35af-4161-9e82-cfc3df54a2b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>5910f29a-6d73-4b7f-bcc6-b97621f7ddb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8bae3a14-8152-4e5a-a80b-a7155d28900a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7eba9a0a-e181-4b1d-b13a-d30a573e24ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>17c913f7-88b8-4129-bfcc-912d31593e21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>ad312b7aacbb</value>
      <webElementGuid>f965e96f-d907-471b-8d16-7354a66b61f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>ad312b7aacbb-7</value>
      <webElementGuid>365a97c5-605a-468c-b5fb-86d08ba31459</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>ad312b7aacbb</value>
      <webElementGuid>7ccac9a9-b1db-4ddb-a7ed-ab7acec86854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-tab-content-1-0&quot;)/div[@class=&quot;mat-tab-body-content ng-tns-c164-3 ng-trigger ng-trigger-translateTab&quot;]/app-unext-campaign-metric-tabel[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;col-span-full tab-wrapper&quot;]/div[@class=&quot;filter-row grid grid-cols-10&quot;]/div[@class=&quot;xmd:col-span-5 md:col-span-7 lg:col-span-8 col-span-7 p-2&quot;]/app-filter-panel[1]/div[@class=&quot;wrapper ng-star-inserted&quot;]/div[@class=&quot;grid grid-cols-10 filter-panel-wrapper align-items-center&quot;]/div[@class=&quot;col-span-full xmd:col-span-full&quot;]/div[@class=&quot;grid grid-cols-12&quot;]/div[@class=&quot;filter-wrapper md:col-span-3 xs:col-span-12 xmd:col-span-4 4k:col-span-2 ng-star-inserted&quot;]/ng-select[@class=&quot;ng-select-multiple ng-select-searchable ng-select-clearable ng-select ng-untouched ng-pristine ng-valid ng-star-inserted ng-select-focused ng-select-bottom ng-select-opened&quot;]/div[@class=&quot;ng-select-container ng-has-value&quot;]/div[@class=&quot;ng-value-container&quot;]/div[@class=&quot;ng-input&quot;]/input[1]</value>
      <webElementGuid>e67fefcb-5b40-42cb-bdd4-29ac6db1bee5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[5]</value>
      <webElementGuid>2bf04c9e-4a00-4030-b2cc-667140c08339</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-1-0']/div/app-unext-campaign-metric-tabel/div/div/div[2]/app-filter-panel/div/div/div/div/div[3]/ng-select/div/div/div[5]/input</value>
      <webElementGuid>b93d11ac-85f4-4788-a80e-5fdb0b79aac0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>19646da6-9cea-4489-8058-6e7f4d50fdf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>6db5fd31-7fa4-497f-a391-59e27924ed79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
