<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Spend Report</name>
   <tag></tag>
   <elementGuidId>6e22b9ca-40b1-451a-b6b1-f4f149191f82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>8d53bad4-66a7-42b6-852b-061d23765612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlinkactive</name>
      <type>Main</type>
      <value>activeLink</value>
      <webElementGuid>0edea4fe-327e-424a-8f87-e336dc7063e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>menu-item</value>
      <webElementGuid>f67ee45b-2a3a-4e41-9d69-be935e715202</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-item ng-star-inserted activeLink</value>
      <webElementGuid>ba704b90-ac83-47a9-a57e-453fd135951c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7e5baecc-ed7c-47e3-aae1-b111e8474a73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu-item-0</value>
      <webElementGuid>9cb5e23c-56f7-47b9-9226-ea19ef445c13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Spend Report</value>
      <webElementGuid>94dfe7cd-7700-401b-94c3-2eadcc6b386f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-0&quot;)</value>
      <webElementGuid>cc2c9dfd-5baa-41e7-93ea-40557ac45f70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='menu-item-0']</value>
      <webElementGuid>1e7a178d-7046-4be1-9ac3-fa55b31d6b25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='sidebarMenu']/li</value>
      <webElementGuid>5eab384a-f33f-4eba-8c9b-bb0b83c245ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='admetrics'])[1]/following::li[1]</value>
      <webElementGuid>c819c186-d680-4a61-9e57-b75ff495cd7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Performance Report'])[1]/preceding::li[1]</value>
      <webElementGuid>3a04d741-0ca7-4903-855d-30d3407823bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li</value>
      <webElementGuid>2b8131f4-114c-4a7d-a9ca-4a160af65ef3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@name = 'menu-item' and @id = 'menu-item-0' and (text() = 'Spend Report' or . = 'Spend Report')]</value>
      <webElementGuid>f56ee457-750c-48bb-be26-0037d53f2df2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
