<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_WIZ_Moonlyte_Buyer_Freelancer_Google_Se_df922d</name>
   <tag></tag>
   <elementGuidId>a9cfd4c0-8553-49eb-85dc-2463c87d8a50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#a9cd4762defc-2 > div.row.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='a9cd4762defc-2']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5b131a9d-f425-4fd4-87a8-f7e2ec904e4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row ng-star-inserted</value>
      <webElementGuid>f30aa849-8e45-47c2-b306-32d6d18e4a74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> WIZ_Moonlyte_Buyer_Freelancer_Google_Search_Ads_Jan_2023 </value>
      <webElementGuid>3a8e450c-4724-4895-b376-9e7b90385436</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a9cd4762defc-2&quot;)/div[@class=&quot;row ng-star-inserted&quot;]</value>
      <webElementGuid>2a841292-766f-41b0-a1a9-0ae74d42aeca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='a9cd4762defc-2']/div</value>
      <webElementGuid>d877c727-8317-4fcc-ac8b-e96f46dc08e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div</value>
      <webElementGuid>1064c2e3-4a8b-4a95-8418-1958d3204e59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' WIZ_Moonlyte_Buyer_Freelancer_Google_Search_Ads_Jan_2023 ' or . = ' WIZ_Moonlyte_Buyer_Freelancer_Google_Search_Ads_Jan_2023 ')]</value>
      <webElementGuid>dada96a8-5f24-4fac-87e6-b501d7ae65bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
