<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Campaign</name>
   <tag></tag>
   <elementGuidId>c9ee126b-da63-4203-b3b9-fb7050fda706</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu-item-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>d7e597c7-66fc-4109-ab08-13c47d440b01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlinkactive</name>
      <type>Main</type>
      <value>activeLink</value>
      <webElementGuid>aaf32ff4-d3a9-43ed-bae7-24f214011333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>menu-item</value>
      <webElementGuid>10ef34f2-ad61-4d75-aec3-6e421b0652f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-item ng-star-inserted</value>
      <webElementGuid>88f4847b-70b8-4767-a5d2-1f290edc11c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ec43e3e9-3ab0-4db9-a9b4-36b5d9fda2ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu-item-3</value>
      <webElementGuid>559632f4-49fb-4189-90b1-de030295b67b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Campaign</value>
      <webElementGuid>a644c4cf-df41-493c-9acb-5b985b1ffddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-3&quot;)</value>
      <webElementGuid>c47f2716-e48e-4809-8a45-bbd35d9d87b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='menu-item-3']</value>
      <webElementGuid>0b8fbbf2-ec03-4773-ba0c-ee78c293aae9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='sidebarMenu']/li[4]</value>
      <webElementGuid>e951c920-af10-44ff-8950-bf99e039a5e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]</value>
      <webElementGuid>0794339e-dc96-4372-9d6a-1d5c130cab20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@name = 'menu-item' and @id = 'menu-item-3' and (text() = 'Campaign' or . = 'Campaign')]</value>
      <webElementGuid>f6b9f28b-54fa-4005-b5f9-5e65350de811</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
