<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-option_20</name>
   <tag></tag>
   <elementGuidId>61bc3ef7-831b-47a5-b90c-032404f42cad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-option[@id='mat-option-2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-option-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-option</value>
      <webElementGuid>815b8cae-8602-4e63-b110-9e36267caf03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>c683a5ae-32df-49cc-a9d3-4d6a18e5cd19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-option mat-focus-indicator ng-tns-c109-8 ng-star-inserted</value>
      <webElementGuid>1dc9773b-a23b-4b61-a021-5f67d8a50181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-option-2</value>
      <webElementGuid>f53e6a88-a2af-4664-8cd1-64c20e97e0a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>50dc3052-05d4-46d8-8e91-c5c1655b2fc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5d06c4db-e85d-4273-a04b-b1794deb0560</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 20 </value>
      <webElementGuid>138cdd18-1a36-4946-b746-dd56f922229c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-option-2&quot;)</value>
      <webElementGuid>3a7001cd-427c-4dac-8915-c3c22c991b52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-option[@id='mat-option-2']</value>
      <webElementGuid>139be614-721a-4bff-853b-091acf105314</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mat-select-0-panel']/mat-option[3]</value>
      <webElementGuid>ee056e46-baee-43db-95fb-e4728e17741d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort'])[1]/following::mat-option[3]</value>
      <webElementGuid>0496be86-9b6f-4735-92ea-080200c28eec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/following::mat-option[3]</value>
      <webElementGuid>6068a2ce-1ce0-4fd9-b4da-80bf1b179ffc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-option[3]</value>
      <webElementGuid>24f7194e-4611-4e9d-b6a2-e0511e5c1784</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-option[@id = 'mat-option-2' and (text() = ' 20 ' or . = ' 20 ')]</value>
      <webElementGuid>965a29f6-2bfb-4407-a0c6-d4eecc54435a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
