<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Grand Total</name>
   <tag></tag>
   <elementGuidId>370929b9-f8f7-495e-89ce-fd03c707670c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mat-sort-header-content.ng-tns-c99-33</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='table1']/app-total-projects-by-source-channel-table/div/div/div/app-material-heat-chart-drilldown-table/div/table/thead/tr/th[5]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ecc5e215-18e1-4aee-9d51-1673669fffb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-sort-header-content ng-tns-c99-33</value>
      <webElementGuid>fd46285e-41db-4d18-af19-2be2bce4fb1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Grand Total</value>
      <webElementGuid>3b2fd90f-7c40-4437-a0db-aba4f76d77c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-tab-content-2-2&quot;)/div[@class=&quot;mat-tab-body-content ng-tns-c164-18 ng-trigger ng-trigger-translateTab&quot;]/app-daily-buyer-cac-trendline-chart[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;col-span-full tab-wrapper&quot;]/div[@class=&quot;reports-row&quot;]/div[@class=&quot;row-wrapper grid grid-cols-2 gap-4&quot;]/div[@id=&quot;table1&quot;]/app-total-projects-by-source-channel-table[1]/div[@class=&quot;component-wrapper&quot;]/div[@class=&quot;chart-wrapper&quot;]/div[@class=&quot;xs:col-span-full text-center py-2 ng-star-inserted&quot;]/app-material-heat-chart-drilldown-table[1]/div[@class=&quot;Mattable&quot;]/table[@class=&quot;mat-table cdk-table mat-sort&quot;]/thead[1]/tr[@class=&quot;mat-header-row cdk-header-row ng-star-inserted&quot;]/th[@class=&quot;mat-sort-header mat-header-cell cdk-header-cell text-neutral-600 xmd:text-sm md:text-md ng-tns-c99-33 cdk-column-Grand-Total mat-column-Grand-Total ng-star-inserted mat-table-sticky mat-table-sticky-border-elem-top cdk-focused cdk-mouse-focused&quot;]/div[@class=&quot;mat-sort-header-container mat-focus-indicator ng-tns-c99-33&quot;]/div[@class=&quot;mat-sort-header-content ng-tns-c99-33&quot;]</value>
      <webElementGuid>0f291bdc-1e80-4c14-8690-152123df0b04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='table1']/app-total-projects-by-source-channel-table/div/div/div/app-material-heat-chart-drilldown-table/div/table/thead/tr/th[5]/div/div</value>
      <webElementGuid>3254a240-ef5b-4332-9076-5579c216191f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[5]/div/div</value>
      <webElementGuid>fcce3c5a-9351-4009-ac52-0d1ee939541d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Grand Total' or . = 'Grand Total')]</value>
      <webElementGuid>0ee00f6e-176c-4837-8b72-cff506d271c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
