<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_WIZ_Moonlyte_Buyer_Freelancer_Google_Se_df922d</name>
   <tag></tag>
   <elementGuidId>c24f1144-a28b-4532-8f42-9fce2afd3db3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mat-sort-header-content.ng-tns-c99-22</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='table1']/app-total-projects-by-source-campaign-table/div/div/div/app-material-heat-chart-drilldown-table/div/table/thead/tr/th[5]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8b2473d5-9e0d-40bd-b02e-23b9889d949b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-sort-header-content ng-tns-c99-22</value>
      <webElementGuid>3521e4f7-4d9f-4c9e-9b76-6223d2f92d9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>WIZ_Moonlyte_Buyer_Freelancer_Google_Search_Ads_Jan_2023</value>
      <webElementGuid>a52f90b4-33ad-4940-8c00-a0a6879e54ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-tab-content-1-2&quot;)/div[@class=&quot;mat-tab-body-content ng-tns-c164-7 ng-trigger ng-trigger-translateTab&quot;]/app-daily-buyer-cac-trendline-chart[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;col-span-full tab-wrapper&quot;]/div[@class=&quot;reports-row&quot;]/div[@class=&quot;row-wrapper grid grid-cols-2 gap-4&quot;]/div[@id=&quot;table1&quot;]/app-total-projects-by-source-campaign-table[1]/div[@class=&quot;component-wrapper&quot;]/div[@class=&quot;chart-wrapper&quot;]/div[@class=&quot;xs:col-span-full text-center py-2 ng-star-inserted&quot;]/app-material-heat-chart-drilldown-table[1]/div[@class=&quot;Mattable&quot;]/table[@class=&quot;mat-table cdk-table mat-sort&quot;]/thead[1]/tr[@class=&quot;mat-header-row cdk-header-row ng-star-inserted&quot;]/th[@class=&quot;mat-sort-header mat-header-cell cdk-header-cell text-neutral-600 xmd:text-sm md:text-md ng-tns-c99-22 cdk-column-WIZ_Moonlyte_Buyer_Freelancer_Google_Search_Ads_Jan_2023 mat-column-WIZ_Moonlyte_Buyer_Freelancer_Google_Search_Ads_Jan_2023 ng-star-inserted mat-table-sticky mat-table-sticky-border-elem-top cdk-focused cdk-mouse-focused&quot;]/div[@class=&quot;mat-sort-header-container mat-focus-indicator ng-tns-c99-22&quot;]/div[@class=&quot;mat-sort-header-content ng-tns-c99-22&quot;]</value>
      <webElementGuid>6f2f7356-d157-4bf6-b66d-3c2be4fe93f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='table1']/app-total-projects-by-source-campaign-table/div/div/div/app-material-heat-chart-drilldown-table/div/table/thead/tr/th[5]/div/div</value>
      <webElementGuid>d4bfa3de-7c53-4273-86ca-e64035532198</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-total-projects-by-source-campaign-table/div/div/div/app-material-heat-chart-drilldown-table/div/table/thead/tr/th[5]/div/div</value>
      <webElementGuid>d0b22293-69cb-4ef3-b094-5b8ae0b56064</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'WIZ_Moonlyte_Buyer_Freelancer_Google_Search_Ads_Jan_2023' or . = 'WIZ_Moonlyte_Buyer_Freelancer_Google_Search_Ads_Jan_2023')]</value>
      <webElementGuid>4fe24401-8f38-4258-a073-3a7f46ee6a3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
