<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Performance</name>
   <tag></tag>
   <elementGuidId>4f0ecb38-1601-46f1-b0d8-a6a51a58b3ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu-item-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>559aef80-8ed1-48e1-bce6-4dc473409ae5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlinkactive</name>
      <type>Main</type>
      <value>activeLink</value>
      <webElementGuid>017a378b-831e-4868-a1b2-724ee19133e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>menu-item</value>
      <webElementGuid>ca6fd3ec-c27c-40a4-a9f5-f867a44717e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-item ng-star-inserted</value>
      <webElementGuid>20403608-f6e0-4c33-a50a-1f4bddf1e7c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fbd173b3-a6c2-489d-b925-31ef1cb4b488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu-item-2</value>
      <webElementGuid>f58f81e6-b225-4905-a6aa-a8374bdfc6d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Performance</value>
      <webElementGuid>699d1141-0831-434d-ada8-7ce46ce534b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-2&quot;)</value>
      <webElementGuid>9d101a2b-7cf2-4a7c-91d6-1a90578cf393</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='menu-item-2']</value>
      <webElementGuid>284dadde-c8f6-4c48-ba91-57a53c967670</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='sidebarMenu']/li[3]</value>
      <webElementGuid>808cd1f2-c5a2-4f8c-99f7-ad455e267cad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]</value>
      <webElementGuid>0d8b75ce-c7b7-4b5e-b789-f715a46d8e15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@name = 'menu-item' and @id = 'menu-item-2' and (text() = 'Performance' or . = 'Performance')]</value>
      <webElementGuid>6fd7e67c-ee7a-4e1d-a699-069ce54fa202</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
