<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_PAUSED</name>
   <tag></tag>
   <elementGuidId>702e57d3-d97e-4204-854b-d053ea37bec3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#a177651a9929-4 > span.ng-option-label.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='a177651a9929-4']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>14ba12bf-3e07-48f5-bd6d-279168ec6910</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option-label ng-star-inserted</value>
      <webElementGuid>e94ab1b9-7721-4e2f-b9de-9d72572af4f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PAUSED</value>
      <webElementGuid>fedce43f-0d41-4889-8f31-b5bbaeb827a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a177651a9929-4&quot;)/span[@class=&quot;ng-option-label ng-star-inserted&quot;]</value>
      <webElementGuid>90fa6d09-9d9e-4d0d-a81b-95700a9a5c7d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='a177651a9929-4']/span</value>
      <webElementGuid>9bffea28-c2d9-4f82-a02c-8ce2ca8070e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/span</value>
      <webElementGuid>2f9b1130-6acc-4f29-9ff8-c79dbabb1731</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'PAUSED' or . = 'PAUSED')]</value>
      <webElementGuid>b5d833d6-ef74-4b73-a8b3-26db47648cb9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
