<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_User ID_logoImg mr-3</name>
   <tag></tag>
   <elementGuidId>a1515c08-4aa1-4f4a-8d68-d29ffbee0608</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='background']/div/div/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.logoImg.mr-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>fc98716b-5189-4731-a28b-3dafea5d7e94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>logoImg mr-3</value>
      <webElementGuid>f4722773-23f7-4350-896b-c428236243e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>./../../../../../assets/images/admetric_logo.png</value>
      <webElementGuid>03bacee0-fdc6-4d7d-854e-1de4fbf62462</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;background&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-4 col-md-6 col-sm-12&quot;]/div[1]/div[@class=&quot;logo&quot;]/div[@class=&quot;logoI&quot;]/img[@class=&quot;logoImg mr-3&quot;]</value>
      <webElementGuid>8388174a-7a18-4f2f-91df-3fff10838ea5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='background']/div/div/div/div/div/img</value>
      <webElementGuid>b85ab5f5-0046-44a5-b292-cfcd531d28f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>758a773f-7800-42cf-a5d0-ec52d7b21fc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = './../../../../../assets/images/admetric_logo.png']</value>
      <webElementGuid>904e8d29-8282-4d7f-a60d-e77e34db0d55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
