<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Facebook</name>
   <tag></tag>
   <elementGuidId>c591ea7e-ef6f-48c9-a3df-4bb6ee7440a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#a6657b7781cf-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='a6657b7781cf-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b4c579ac-6af3-4f38-b079-c596f870b069</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option ng-star-inserted ng-option-marked</value>
      <webElementGuid>d7c50dbe-0cc2-4c35-b137-5a40ddb43db4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>19a32a72-ec8e-455b-b438-a7b79540306a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>22523813-710f-4598-b1df-2b17e19bf7f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a6657b7781cf-1</value>
      <webElementGuid>f797c10b-6a0e-48d4-a0a3-92d83ce4e5f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Facebook</value>
      <webElementGuid>1f7df760-d5bf-43c3-b1fa-345cf9bb0a1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a6657b7781cf-1&quot;)</value>
      <webElementGuid>3d11d1de-5135-4637-9e61-70e037b07c25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='a6657b7781cf-1']</value>
      <webElementGuid>7e87927e-1e73-404a-8018-fc70999b5bd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='a6657b7781cf']/div/div[2]/div[2]</value>
      <webElementGuid>b7f0b874-11ba-4b18-9aa1-7015b1eed3d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div[2]</value>
      <webElementGuid>98a9b204-c38c-4b73-b1d2-5a6b640491f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'a6657b7781cf-1' and (text() = 'Facebook' or . = 'Facebook')]</value>
      <webElementGuid>b897d934-a161-4707-baf8-1ef8c6e59056</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
