<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_MTD Spend Monitoring</name>
   <tag></tag>
   <elementGuidId>3e92e162-bfda-4c47-99bf-f071ce4ca650</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-tab-label-1-2 > div.mat-tab-label-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mat-tab-label-1-2']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f357c1b1-b13b-4cb7-8cee-55ae9016c7b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-tab-label-content</value>
      <webElementGuid>fa2a0062-20e0-4d8a-b72b-1cdfe5d9f179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MTD Spend Monitoring</value>
      <webElementGuid>3248d7fc-6082-4818-b603-b87269867401</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-tab-label-1-2&quot;)/div[@class=&quot;mat-tab-label-content&quot;]</value>
      <webElementGuid>d7577cf8-030d-4209-9a1a-6caf17c43ecd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mat-tab-label-1-2']/div</value>
      <webElementGuid>2b5328c4-a80a-43c5-9277-d561f25ee830</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div</value>
      <webElementGuid>2993e0ea-4626-43ed-8a7c-1d20b3057613</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'MTD Spend Monitoring' or . = 'MTD Spend Monitoring')]</value>
      <webElementGuid>ae5d9614-ef6c-419c-b6b5-ea550259ba11</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
