<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>d8dba68a-4879-437a-b6f6-c490b17fd3bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fullscreen-button > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='fullscreen-button']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>eb7cce94-02fe-4a29-a80a-a0a8ff003ebd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>17</value>
      <webElementGuid>93d3b994-d2be-4b80-b81c-dd5df1986e7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/images/full-screen_img.png</value>
      <webElementGuid>d902daff-dacf-412b-9bee-03639c918282</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fullscreen-button&quot;)/img[1]</value>
      <webElementGuid>c7cb99f1-469b-4f19-b060-aff02de5ee2c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='fullscreen-button']/img</value>
      <webElementGuid>7e5c4f23-348e-4a58-9c5a-8599f553c9c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/img</value>
      <webElementGuid>989991ed-16df-46a1-85b5-cf7bddbb1afc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'assets/images/full-screen_img.png']</value>
      <webElementGuid>4fa97d60-b359-420c-8149-07d0f0448f19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
