<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Buyer</name>
   <tag></tag>
   <elementGuidId>cf4adff9-5754-4dfd-bbd6-9e16e85563a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#a40d287fdf29-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='a40d287fdf29-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9f7833c0-33a7-4724-afba-09c5e408b55d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option ng-star-inserted ng-option-marked</value>
      <webElementGuid>f041dc44-7d1c-4505-9366-0a6c74d538aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>cb53a6de-e673-4c96-aeaf-6e1844dea87b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fb3b8f8a-032f-44ba-9992-08cb1be8ea15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a40d287fdf29-0</value>
      <webElementGuid>8462498b-6bbe-480c-83dc-24cd4b5f1b87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Buyer</value>
      <webElementGuid>6a86188e-15ec-40ae-9e81-6e25cf30a380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a40d287fdf29-0&quot;)</value>
      <webElementGuid>0c70947f-3a25-47e1-9d6b-2ba123885c77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='a40d287fdf29-0']</value>
      <webElementGuid>625b16a1-d894-4e76-b68e-e2d2f7e4f1c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='a40d287fdf29']/div/div[2]/div</value>
      <webElementGuid>e50521df-f8bf-4139-a264-a913ee9a7fda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-dropdown-panel/div/div[2]/div</value>
      <webElementGuid>b8c2f9b2-7824-4478-b5ad-4102aecd0481</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'a40d287fdf29-0' and (text() = 'Buyer' or . = 'Buyer')]</value>
      <webElementGuid>8528f7a6-acdf-4bf1-9d16-90e0f369c174</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
