<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_downloading</name>
   <tag></tag>
   <elementGuidId>cb2634fa-df69-4cc9-ac46-b6cbefee5ab3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='table3']/app-campaign-metric-table/div/div/div/app-csv-data-download-button/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.material-icons</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f9771d25-1a98-4253-9a9b-91c9a58c30a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material-icons</value>
      <webElementGuid>3f4ade5f-d028-472b-be87-834fa1d64a7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> downloading </value>
      <webElementGuid>f55e1240-6711-4712-b66c-b83794839d33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table3&quot;)/app-campaign-metric-table[1]/div[@class=&quot;component-wrapper&quot;]/div[@class=&quot;chart-wrapper&quot;]/div[@class=&quot;xs:col-span-full text-center py-2 ng-star-inserted&quot;]/app-csv-data-download-button[@class=&quot;position-absolute end-3&quot;]/button[@class=&quot;mat-tooltip-trigger cdk-focused cdk-mouse-focused&quot;]/span[@class=&quot;material-icons&quot;]</value>
      <webElementGuid>34fc7d45-4b9e-4bf3-93c8-b871dcc8954e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='table3']/app-campaign-metric-table/div/div/div/app-csv-data-download-button/button/span</value>
      <webElementGuid>1d733732-1792-4c55-9a28-257565fd2faa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-csv-data-download-button/button/span</value>
      <webElementGuid>a6e4c6e3-193a-448e-9fdf-e8a01c8d425e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' downloading ' or . = ' downloading ')]</value>
      <webElementGuid>969a3559-e9f1-4680-9c82-a517d109e90b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
