<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_mat-sort-header-pointer-left ng-tns-c99_37d94a</name>
   <tag></tag>
   <elementGuidId>f5e237a5-a0d8-4f70-9138-7ee0cd2b733f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mat-sort-header-pointer-left.ng-tns-c99-18.ng-trigger.ng-trigger-leftPointer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='table3']/app-campaign-metric-table/div/div/div/app-material-heat-chart-drilldown-table/div/table/thead/tr/th[6]/div/div[2]/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>465cd868-c711-4a8d-ad05-f65ad13b23f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-sort-header-pointer-left ng-tns-c99-18 ng-trigger ng-trigger-leftPointer</value>
      <webElementGuid>c60d9a28-04e2-4d9a-9854-803759f606a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table3&quot;)/app-campaign-metric-table[1]/div[@class=&quot;component-wrapper&quot;]/div[@class=&quot;chart-wrapper&quot;]/div[@class=&quot;xs:col-span-full text-center py-2 ng-star-inserted&quot;]/app-material-heat-chart-drilldown-table[1]/div[@class=&quot;Mattable&quot;]/table[@class=&quot;mat-table cdk-table mat-sort&quot;]/thead[1]/tr[@class=&quot;mat-header-row cdk-header-row ng-star-inserted&quot;]/th[@class=&quot;mat-sort-header mat-header-cell cdk-header-cell text-neutral-600 xmd:text-sm md:text-md ng-tns-c99-18 cdk-column-ctr mat-column-ctr ng-star-inserted mat-table-sticky mat-table-sticky-border-elem-top cdk-focused cdk-mouse-focused&quot;]/div[@class=&quot;mat-sort-header-container mat-focus-indicator ng-tns-c99-18&quot;]/div[@class=&quot;mat-sort-header-arrow ng-trigger ng-trigger-arrowPosition ng-tns-c99-18 ng-star-inserted&quot;]/div[@class=&quot;mat-sort-header-indicator ng-tns-c99-18 ng-trigger ng-trigger-indicator&quot;]/div[@class=&quot;mat-sort-header-pointer-left ng-tns-c99-18 ng-trigger ng-trigger-leftPointer&quot;]</value>
      <webElementGuid>77fc579e-bd9d-43ed-a040-fc121661a2f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='table3']/app-campaign-metric-table/div/div/div/app-material-heat-chart-drilldown-table/div/table/thead/tr/th[6]/div/div[2]/div[2]/div</value>
      <webElementGuid>7badefd0-8a4a-4a36-af05-43e34734d726</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[6]/div/div[2]/div[2]/div</value>
      <webElementGuid>7f2ea0ff-b269-4bbe-b46f-145fd69a4c96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
