<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_mat-sort-header-pointer-right ng-tns-c9_213f72_1</name>
   <tag></tag>
   <elementGuidId>0f6ab5d0-f33c-4d7c-86f7-01fdad6eb98a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mat-sort-header-pointer-right.ng-tns-c99-19.ng-trigger.ng-trigger-rightPointer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='table3']/app-campaign-metric-table/div/div/div/app-material-heat-chart-drilldown-table/div/table/thead/tr/th[7]/div/div[2]/div[2]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>af9929a6-bc74-4fa1-ad91-3ff0e550402f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-sort-header-pointer-right ng-tns-c99-19 ng-trigger ng-trigger-rightPointer</value>
      <webElementGuid>7a2c123e-3ee0-48cd-b644-d5c5dcb998f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table3&quot;)/app-campaign-metric-table[1]/div[@class=&quot;component-wrapper&quot;]/div[@class=&quot;chart-wrapper&quot;]/div[@class=&quot;xs:col-span-full text-center py-2 ng-star-inserted&quot;]/app-material-heat-chart-drilldown-table[1]/div[@class=&quot;Mattable&quot;]/table[@class=&quot;mat-table cdk-table mat-sort&quot;]/thead[1]/tr[@class=&quot;mat-header-row cdk-header-row ng-star-inserted&quot;]/th[@class=&quot;mat-sort-header mat-header-cell cdk-header-cell text-neutral-600 xmd:text-sm md:text-md ng-tns-c99-19 cdk-column-total_reach mat-column-total_reach ng-star-inserted mat-table-sticky mat-table-sticky-border-elem-top cdk-focused cdk-mouse-focused&quot;]/div[@class=&quot;mat-sort-header-container mat-focus-indicator ng-tns-c99-19&quot;]/div[@class=&quot;mat-sort-header-arrow ng-trigger ng-trigger-arrowPosition ng-tns-c99-19 ng-star-inserted ng-animating&quot;]/div[@class=&quot;mat-sort-header-indicator ng-tns-c99-19 ng-trigger ng-trigger-indicator&quot;]/div[@class=&quot;mat-sort-header-pointer-right ng-tns-c99-19 ng-trigger ng-trigger-rightPointer&quot;]</value>
      <webElementGuid>15ee2d51-e512-4f74-bed2-1cbf05fd2e69</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='table3']/app-campaign-metric-table/div/div/div/app-material-heat-chart-drilldown-table/div/table/thead/tr/th[7]/div/div[2]/div[2]/div[2]</value>
      <webElementGuid>23d72d4c-270a-473a-93b1-fa17ccaada8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[7]/div/div[2]/div[2]/div[2]</value>
      <webElementGuid>62f16139-9300-4bda-947e-5848674b80ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
